### PR TITLE
omgx integration

### PR DESCRIPTION
**Pull request by InoMurko**

### CODE REVIEW

**Comment by InoMurko** [comment]
I've deleted `omgx-sync-tests.yml ` because I think it's a duplicate of `sync-tests.yml`.

These tests really just test verifier and replica.


`omgx-integration.yml` has commented out the original Optimism integration tests. The old `develop` had them enabled and the reason for it was that it allowed us check whether our containers somehow interfere with the original containers. Just putting this out there in case @jliphard decides to enable them back.

**Comment by InoMurko** [comment]
I see that creating an omgx docker - compose overlay was commented out:
```
# yq eval '(.services.[].image | select(. == "ethereumoptimism*")) |= sub("ethereumoptimism", "omgx")' ${ORIGINAL_DOCKERFILE} | \
# yq eval '(.services.[].image) += ":latest"' - \
# > ${DOCKERFILE}
```

This means we're relying on Optimisms push of container images into *their* docker hub. Not ours. So their `latest` container could in in front of our containers and there could be discrepancies the way the system is functioning.

**Comment by CAPtheorem** [comment]
Most changes incorporated into #149.

**Comment by InoMurko** [comment]
okay, so should this be closed?

**Comment by CAPtheorem** [comment]
yes, can be closed

**Pull request closed without merging**
